version: '3'
services:
  postgre:
    build:
      context: ./containers/postgre
    ports:
      - 5432:5432
    image: ratatoile_postgre_image
    container_name: ratatoile_postgre
    volumes:
      - ~/ratatoile_data/postgre:/var/lib/postgresql/data
